/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * @author jdmp
 */
@Entity(name = "Departamento")
@Table(name = "departamento")
@NamedQuery(name = "DepartamentoEntity.findByCodigo", query = "Select e from Departamento e WHERE e.codigo = :codigo")
public class DepartamentoEntity extends BaseEntity implements Serializable {

    @Column(name = "dpto_codigo")
    @Basic
    private String codigo;

    @Column(name = "dpto_nombre")
    @Basic
    private String nombre;

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
