/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Version;

@Entity(name = "Empresa")
@Table(name = "empresa")
@NamedQuery(name = "EmpresaEntity.findByNit", query = "Select e from Empresa e WHERE e.nit =:nit")
public class EmpresaEntity implements Serializable {

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;
    
    @Column(name = "emp_direccion")
    @Basic
    private String direccion;

    @Column(name = "emp_nombre", unique = true)
    @Basic
    private String nombre;

    @Column(name = "emp_email_pass")
    @Basic
    private String emailPass;

    @Column(name = "emp_nit")
    @Basic
    private String nit;

    @Column(name = "emp_email_host")
    @Basic
    private String emailHost;

    @Column(name = "emp_telefono")
    @Basic
    private String telefono;

    @Column(name = "emp_email_port")
    @Basic
    private String emailPort;

    @Column(name = "emp_email")
    @Basic
    private String email;

    @ManyToOne(targetEntity = PobladoEntity.class)
    @JoinColumn(name = "POBLADO_ID")
    private PobladoEntity poblado;
    
    @ManyToOne(targetEntity = Archivo.class)
    @JoinColumn(name = "ARCHIVO_ID")
    private Archivo logo;
    
    @Version
    private int version;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getEmailPass() {
        return this.emailPass;
    }

    public void setEmailPass(String emailPass) {
        this.emailPass = emailPass;
    }

    public String getNit() {
        return this.nit;
    }

    public void setNit(String nit) {
        this.nit = nit;
    }

    public String getEmailHost() {
        return this.emailHost;
    }

    public void setEmailHost(String emailHost) {
        this.emailHost = emailHost;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getEmailPort() {
        return this.emailPort;
    }

    public void setEmailPort(String emailPort) {
        this.emailPort = emailPort;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public PobladoEntity getPoblado() {
        return this.poblado;
    }

    public void setPoblado(PobladoEntity poblado) {
        this.poblado = poblado;
    }

    public Archivo getLogo() {
        return logo;
    }

    public void setLogo(Archivo logo) {
        this.logo = logo;
    }
    
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {return false;}
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {return false;}
        final EmpresaEntity other = (EmpresaEntity) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {return false;}
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 41 * hash + (this.getId() != null ? this.getId().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "EmpresaEntity{" + " id=" + id + '}';
    }

}
