/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * @author jdmp
 */
@Entity(name = "EstadoInmueble")
@Table(name = "estado_inmueble")
public class EstadoInmuebleEntity extends BaseEntity implements Serializable {

    @Column(name = "ei_nombre")
    @Basic
    private String nombre;

    @Basic
    private String codigo;

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

}
