/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * @author jkelsy
 */
@Entity(name = "EstadoNegociacion")
@Table(name = "estado_negociacion")
public class EstadoNegociacionEntity extends BaseEntity implements Serializable {

    @Column(name = "en_codigo")
    @Basic
    private String codigo;

    @Column(name = "en_nombre")
    @Basic
    private String nombre;

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
