/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * @author jkelsy
 */
@Entity(name = "Inmueble")
@Table(name = "inmueble")
@NamedQueries({
    @NamedQuery(name = "Inmueble.findByProyecto", query = "Select i from Inmueble i WHERE i.proyecto.id = :proyecto_id"),
    @NamedQuery(name = "Inmueble.findByProyectoAndEstado", query = "Select i from Inmueble i WHERE i.proyecto.id = :proyecto_id AND i.estadoInmueble.id = :estado_id")})
public class InmuebleEntity extends BaseEntity implements Serializable {

    @Column(name = "inm_numero")
    @Basic
    private String numero;

    @Column(name = "inm_area")
    @Basic
    private Double area;

    @Column(name = "inm_valor_metro_cuadrado")
    @Basic
    private Double valorMetroCuadrado;

    @Column(name = "inm_incremento")
    @Basic
    private Double incremento;

    @Column(name = "inm_valor_separacion")
    @Basic
    private Double valorSeparacion;

    @Column(name = "inm_valor_total")
    @Basic
    private Double valorTotal;

    @ManyToOne(targetEntity = ProyectoEntity.class)
    @JoinColumn(name = "PROYECTO_ID")
    private ProyectoEntity proyecto;

    @ManyToOne(targetEntity = EstadoInmuebleEntity.class)
    @JoinColumn(name = "ESTADOINMUEBLE_ID")
    private EstadoInmuebleEntity estadoInmueble;

    @ManyToOne(targetEntity = Piso.class)
    @JoinColumn(name = "PISO_ID")
    private Piso piso;

    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public Double getArea() {
        return this.area;
    }

    public void setArea(Double area) {
        this.area = area;
    }

    public Double getValorMetroCuadrado() {
        return this.valorMetroCuadrado;
    }

    public void setValorMetroCuadrado(Double valorMetroCuadrado) {
        this.valorMetroCuadrado = valorMetroCuadrado;
    }

    public Double getIncremento() {
        return this.incremento;
    }

    public void setIncremento(Double incremento) {
        this.incremento = incremento;
    }

    public Double getValorSeparacion() {
        return this.valorSeparacion;
    }

    public void setValorSeparacion(Double valorSeparacion) {
        this.valorSeparacion = valorSeparacion;
    }

    public Double getValorTotal() {
        return this.valorTotal;
    }

    public void setValorTotal(Double valorTotal) {
        this.valorTotal = valorTotal;
    }

    public ProyectoEntity getProyecto() {
        return this.proyecto;
    }

    public void setProyecto(ProyectoEntity proyecto) {
        this.proyecto = proyecto;
    }

    public EstadoInmuebleEntity getEstadoInmueble() {
        return this.estadoInmueble;
    }

    public void setEstadoInmueble(EstadoInmuebleEntity estadoInmueble) {
        this.estadoInmueble = estadoInmueble;
    }

    public Piso getPiso() {
        return this.piso;
    }

    public void setPiso(Piso piso) {
        this.piso = piso;
    }

}
