/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * @author jdmp
 */
@Entity(name = "Municipio")
@Table(name = "municipio")
public class MunicipioEntity extends BaseEntity implements Serializable {

    @Column(name = "mun_codigo")
    @Basic
    private String codigo;

    @Column(name = "mun_nombre")
    @Basic
    private String nombre;

    @ManyToOne(targetEntity = DepartamentoEntity.class)
    @JoinColumn(name = "DEPARTAMENTO_ID")
    private DepartamentoEntity departamento;

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public DepartamentoEntity getDepartamento() {
        return this.departamento;
    }

    public void setDepartamento(DepartamentoEntity departamento) {
        this.departamento = departamento;
    }

}
