/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity(name = "Negociacion")
@Table(name = "negociacion")
public class NegociacionEntity implements Serializable {
    
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Column(name = "neg_codigo")
    @Basic
    private String codigo;

    @Column(name = "neg_fecha")
    @Basic
    private Date fecha;
    
    @Column(name = "neg_fecha_primera_cuota")
    @Basic
    private Date fechaPrimeraCuota;

    @Column(name = "neg_valor_metro_cuadrado")
    @Basic
    private Double valorMetroCuadrado;

    @Column(name = "neg_valor_separacion")
    @Basic
    private Double valorSeparacion;

    @Column(name = "neg_numero_cuotas")
    @Basic
    private Integer numeroCuotas;

    @Column(name = "neg_valor_incremento")
    @Basic
    private Double valorIncremento;

    @Column(name = "neg_valor_total")
    @Basic
    private Double valorTotal;

    @Column(name = "neg_porcentaje")
    @Basic
    private Double porcentaje;
    
    @Column(name = "neg_valor_porcentaje")
    @Basic
    private Double valorPorcentaje;
    
    @Column(name = "neg_valor_descuento")
    @Basic
    private Double valorDescuento;
    
    @Column(name = "neg_observacion")
    @Basic
    private String observacion;

    @OneToOne(targetEntity = InmuebleEntity.class)
    @JoinColumn(name = "INMUEBLE_ID")
    private InmuebleEntity inmueble;

    @OneToOne(targetEntity = OfertaEntity.class)
    @JoinColumn(name = "OFERTA_ID")
    private OfertaEntity oferta;

    @ManyToOne(targetEntity = UsuarioEntity.class)
    @JoinColumn(name = "SUPERVISOR_ID")
    private UsuarioEntity supervisor;

    @ManyToOne(targetEntity = EstadoNegociacionEntity.class)
    @JoinColumn(name = "ESTADO_NEGOCIACION_ID")
    private EstadoNegociacionEntity estadoNegociacion;

    @ManyToOne(targetEntity = UsuarioEntity.class)
    @JoinColumn(name = "VENDEDOR_ID")
    private UsuarioEntity vendedor;
    
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Date getFechaPrimeraCuota() {
        return fechaPrimeraCuota;
    }

    public void setFechaPrimeraCuota(Date fechaPrimeraCuota) {
        this.fechaPrimeraCuota = fechaPrimeraCuota;
    }

    public Double getValorMetroCuadrado() {
        return this.valorMetroCuadrado;
    }

    public void setValorMetroCuadrado(Double valorMetroCuadrado) {
        this.valorMetroCuadrado = valorMetroCuadrado;
    }

    public Double getValorSeparacion() {
        return this.valorSeparacion;
    }

    public void setValorSeparacion(Double valorSeparacion) {
        this.valorSeparacion = valorSeparacion;
    }

    public Integer getNumeroCuotas() {
        return this.numeroCuotas;
    }

    public void setNumeroCuotas(Integer numeroCuotas) {
        this.numeroCuotas = numeroCuotas;
    }

    public Double getValorIncremento() {
        return this.valorIncremento;
    }

    public void setValorIncremento(Double valorIncremento) {
        this.valorIncremento = valorIncremento;
    }

    public Double getValorTotal() {
        return this.valorTotal;
    }

    public void setValorTotal(Double valorTotal) {
        this.valorTotal = valorTotal;
    }

    public Double getPorcentaje() {
        return this.porcentaje;
    }

    public void setPorcentaje(Double porcentaje) {
        this.porcentaje = porcentaje;
    }

    public Double getValorPorcentaje() {
        return valorPorcentaje;
    }

    public void setValorPorcentaje(Double valorPorcentaje) {
        this.valorPorcentaje = valorPorcentaje;
    }

    public InmuebleEntity getInmueble() {
        return this.inmueble;
    }

    public void setInmueble(InmuebleEntity inmueble) {
        this.inmueble = inmueble;
    }

    public OfertaEntity getOferta() {
        return this.oferta;
    }

    public void setOferta(OfertaEntity oferta) {
        this.oferta = oferta;
    }

    public UsuarioEntity getSupervisor() {
        return this.supervisor;
    }

    public void setSupervisor(UsuarioEntity supervisor) {
        this.supervisor = supervisor;
    }

    public EstadoNegociacionEntity getEstadoNegociacion() {
        return this.estadoNegociacion;
    }

    public void setEstadoNegociacion(EstadoNegociacionEntity estadoNegociacion) {
        this.estadoNegociacion = estadoNegociacion;
    }

    public UsuarioEntity getVendedor() {
        return this.vendedor;
    }

    public void setVendedor(UsuarioEntity vendedor) {
        this.vendedor = vendedor;
    }

    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public Double getValorDescuento() {
        return valorDescuento;
    }

    public void setValorDescuento(Double valorDescuento) {
        this.valorDescuento = valorDescuento;
    }
    
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {return false;}
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {return false;}
        final NegociacionEntity other = (NegociacionEntity) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {return false;}
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 41 * hash + (this.getId() != null ? this.getId().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "NegociacionEntity{" + " id=" + id + '}';
    }

}
