/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * @author jdmp
 */
@Entity(name = "Permiso")
@Table(name = "sec_permiso")
public class PermisoEntity extends BaseEntity implements Serializable {

    @ManyToOne(cascade = {CascadeType.ALL}, targetEntity = UsuarioEntity.class)
    @JoinColumn(name = "USUARIO_USR_ID")
    private UsuarioEntity usuario;

    @ManyToOne(cascade = {CascadeType.ALL}, targetEntity = RolEntity.class)
    @JoinColumn(name = "ROL_ROL_ID")
    private RolEntity rol;

    public UsuarioEntity getUsuario() {
        return this.usuario;
    }

    public void setUsuario(UsuarioEntity usuario) {
        this.usuario = usuario;
    }

    public RolEntity getRol() {
        return this.rol;
    }

    public void setRol(RolEntity rol) {
        this.rol = rol;
    }

}
