/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * @author jkelsy
 */
@Entity(name = "Permiso")
@Table(name = "sec_permiso")
public class PermisoEntity implements Serializable {
    
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;
    
    @Version
    private int version;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }
    
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {

    	if (this == obj) {
    		return true;
    	} else if (obj == null) {
            return false;
        } else if (obj.getClass() != this.getClass()) {
            return false;
        }else {
            return false;
        }
    }

    @Override
    public String toString() {
    	return String.format("%s[id=%d]", getClass().getSimpleName(), getId());
    }

    @ManyToOne(targetEntity = UsuarioEntity.class)
    @JoinColumn(name = "USUARIO_USR_ID")
    private UsuarioEntity usuario;

    @ManyToOne(targetEntity = RolEntity.class)
    @JoinColumn(name = "ROL_ROL_ID")
    private RolEntity rol;

    public UsuarioEntity getUsuario() {
        return this.usuario;
    }

    public void setUsuario(UsuarioEntity usuario) {
        this.usuario = usuario;
    }

    public RolEntity getRol() {
        return this.rol;
    }

    public void setRol(RolEntity rol) {
        this.rol = rol;
    }

}
