/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * @author jdmp
 */
@Entity(name = "Poblado")
@Table(name = "poblado")
public class PobladoEntity extends BaseEntity implements Serializable {

    @Column(name = "pob_codigo")
    @Basic
    private String codigo;

    @Column(name = "pob_nombre")
    @Basic
    private String nombre;

    @ManyToOne(cascade = {CascadeType.ALL}, targetEntity = MunicipioEntity.class)
    @JoinColumn(name = "MUNICIPIO_ID")
    private MunicipioEntity municipio;

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public MunicipioEntity getMunicipio() {
        return this.municipio;
    }

    public void setMunicipio(MunicipioEntity municipio) {
        this.municipio = municipio;
    }

}
