/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * @author jdmp
 */
@Entity(name = "Rol")
@Table(name = "sec_rol")
public class RolEntity extends BaseEntity implements Serializable {

    @Column(name = "rol_nombre")
    @Basic
    private String nombre;

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
