/**
 * This file was generated by the Jeddict
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Version;

@Entity(name = "Tercero")
@Table(name = "tercero")
@NamedQuery(name = "TerceroEntity.findByIdentificacion", query = "Select t from Tercero t WHERE t.identificacion=:identificacion")
public class TerceroEntity implements Serializable {

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;
    
    @Column(name = "ter_apellido2")
    @Basic
    private String apellido2;

    @Column(name = "ter_apellido1")
    @Basic
    private String apellido1;

    @Column(name = "ter_direccion")
    @Basic
    private String direccion;

    @Column(name = "ter_identificacion")
    @Basic
    private String identificacion;

    @Column(name = "ter_telefono")
    @Basic
    private String telefono;
    
    @Column(name = "ter_celular")
    @Basic
    private String celular;

    @Column(name = "ter_email")
    @Basic
    private String email;

    @Column(name = "ter_nombres")
    @Basic
    private String nombres;
    
    @Column(name = "ter_sexo")
    @Basic
    private String sexo;
    
    @Column(name = "ter_estado_civil")
    @Basic
    private String estadoCivil;
    
    @Column(name = "ter_barrio")
    @Basic
    private String barrio;
    
    @Column(name = "ter_ocupacion")
    @Basic
    private String ocupacion;
    
    @Column(name = "ter_otra_fuente")
    @Basic
    private String otraFuente;

    @ManyToOne(targetEntity = TipoIdentificacionEntity.class)
    @JoinColumn(name = "TIPO_IDENTIFICACION_ID")
    private TipoIdentificacionEntity tipoIdentificacion;
    
    @ManyToOne(targetEntity = TipoFuenteInformacionEntity.class)
    @JoinColumn(name = "TIPO_FUENTE_INFORMACION_ID")
    private TipoFuenteInformacionEntity tipoFuenteInformacion;

    @ManyToOne(targetEntity = PobladoEntity.class)
    @JoinColumn(name = "LUGAR_EXPEDICION_ID")
    private PobladoEntity lugarExpedicion;
    
    @ManyToOne(targetEntity = PobladoEntity.class)
    @JoinColumn(name = "LUGAR_NACIMIENTO_ID")
    private PobladoEntity lugarNacimiento;
    
    @ManyToOne(targetEntity = PobladoEntity.class)
    @JoinColumn(name = "LUGAR_RESIDENCIA_ID")
    private PobladoEntity lugarResidencia;

    @ManyToOne(targetEntity = UsuarioEntity.class)
    @JoinColumn(name = "USUARIO_ID")    
    private UsuarioEntity usuario;
    
    @Version
    private int version;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getApellido2() {
        return this.apellido2;
    }

    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }

    public String getApellido1() {
        return this.apellido1;
    }

    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getIdentificacion() {
        return this.identificacion;
    }

    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public TipoIdentificacionEntity getTipoIdentificacion() {
        return this.tipoIdentificacion;
    }

    public void setTipoIdentificacion(TipoIdentificacionEntity tipoIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
    }

    public PobladoEntity getLugarExpedicion() {
        return this.lugarExpedicion;
    }

    public void setLugarExpedicion(PobladoEntity lugarExpedicion) {
        this.lugarExpedicion = lugarExpedicion;
    }

    public PobladoEntity getLugarNacimiento() {
        return lugarNacimiento;
    }

    public void setLugarNacimiento(PobladoEntity lugarNacimiento) {
        this.lugarNacimiento = lugarNacimiento;
    }   

    public PobladoEntity getLugarResidencia() {
        return lugarResidencia;
    }

    public void setLugarResidencia(PobladoEntity lugarResidencia) {
        this.lugarResidencia = lugarResidencia;
    }

    public UsuarioEntity getUsuario() {
        return this.usuario;
    }

    public void setUsuario(UsuarioEntity usuario) {
        this.usuario = usuario;
    }

    public TipoFuenteInformacionEntity getTipoFuenteInformacion() {
        return tipoFuenteInformacion;
    }

    public void setTipoFuenteInformacion(TipoFuenteInformacionEntity tipoFuenteInformacion) {
        this.tipoFuenteInformacion = tipoFuenteInformacion;
    }

    public String getOtraFuente() {
        return otraFuente;
    }

    public void setOtraFuente(String otraFuente) {
        this.otraFuente = otraFuente;
    }

    public String getSexo() {
        return sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    public String getEstadoCivil() {
        return estadoCivil;
    }

    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    public String getCelular() {
        return celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    public String getBarrio() {
        return barrio;
    }

    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }

    public String getOcupacion() {
        return ocupacion;
    }

    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {return false;}
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {return false;}
        final TerceroEntity other = (TerceroEntity) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {return false;        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 41 * hash + (this.getId() != null ? this.getId().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "TerceroEntity{" + " id=" + id + '}';
    }
    
    public String getNombreCompleto() {
        String tempo = "";        
        
        tempo += (nombres!=null)?nombres:"";
        tempo += " ";
        tempo += (apellido1!=null)?apellido1:"";
        tempo += " ";
        tempo += (apellido2!=null)?apellido2:"";
        
        return tempo.toUpperCase(); 
    }

}
