/**
 * This file was generated by the Jeddict
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Version;

@Entity(name = "Tercero")
@Table(name = "tercero")
@NamedQuery(name = "TerceroEntity.findByIdentificacion", query = "Select t from Tercero t WHERE t.identificacion=:identificacion")
public class TerceroEntity implements Serializable {

    @Column(name="ter_id")
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;
    
    @Column(name = "ter_apellido2")
    @Basic
    private String apellido2;

    @Column(name = "ter_apellido1")
    @Basic
    private String apellido1;

    @Column(name = "ter_direccion")
    @Basic
    private String direccion;

    @Column(name = "ter_identificacion")
    @Basic
    private String identificacion;

    @Column(name = "ter_telefono")
    @Basic
    private String telefono;

    @Column(name = "ter_email")
    @Basic
    private String email;

    @Column(name = "ter_nombres")
    @Basic
    private String nombres;

    @ManyToOne(targetEntity = TipoIdentificacionEntity.class)
    @JoinColumn(name = "TIPO_IDENTIFICACION_ID", referencedColumnName = "ID")
    private TipoIdentificacionEntity tipoIdentificacion;

    @ManyToOne(targetEntity = PobladoEntity.class)
    @JoinColumn(name = "LUGAR_EXPEDICION_ID")
    private PobladoEntity lugarExpedicion;

    @ManyToOne(targetEntity = UsuarioEntity.class)
    @JoinColumn(name = "USUARIO_ID")    
    private UsuarioEntity usuario;
    
    @Version
    private int version;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getApellido2() {
        return this.apellido2;
    }

    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }

    public String getApellido1() {
        return this.apellido1;
    }

    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getIdentificacion() {
        return this.identificacion;
    }

    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public TipoIdentificacionEntity getTipoIdentificacion() {
        return this.tipoIdentificacion;
    }

    public void setTipoIdentificacion(TipoIdentificacionEntity tipoIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
    }

    public PobladoEntity getLugarExpedicion() {
        return this.lugarExpedicion;
    }

    public void setLugarExpedicion(PobladoEntity lugarExpedicion) {
        this.lugarExpedicion = lugarExpedicion;
    }

    public UsuarioEntity getUsuario() {
        return this.usuario;
    }

    public void setUsuario(UsuarioEntity usuario) {
        this.usuario = usuario;
    }
    
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {

    	if (this == obj) {
    		return true;
    	} else if (obj == null) {
            return false;
        } else if (obj.getClass() != this.getClass()) {
            return false;
        }else {
            return false;
        }
    }

    @Override
    public String toString() {
    	return String.format("%s[id=%d]", getClass().getSimpleName(), getId());
    }

}
