/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * @author jkelsy
 */
@Entity(name = "TipoPlantaDetalle")
@Table(name = "tipo_planta_detalle")
public class TipoPlantaDetalleEntity extends BaseEntity implements Serializable {

    @Basic
    private Integer numero;

    @ManyToOne(targetEntity = TipoPlantaEntity.class)
    private TipoPlantaEntity tipoPlanta;

    @ManyToOne(targetEntity = TipoInmuebleEntity.class)
    private TipoInmuebleEntity tipoInmueble;

    public Integer getNumero() {
        return this.numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    public TipoPlantaEntity getTipoPlanta() {
        return this.tipoPlanta;
    }

    public void setTipoPlanta(TipoPlantaEntity tipoPlanta) {
        this.tipoPlanta = tipoPlanta;
    }

    public TipoInmuebleEntity getTipoInmueble() {
        return this.tipoInmueble;
    }

    public void setTipoInmueble(TipoInmuebleEntity tipoInmueble) {
        this.tipoInmueble = tipoInmueble;
    }

}
