/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * @author jdmp
 */
@Entity(name = "TipoInmueble")
@Table(name = "tipo_inmueble")
public class TipoInmuebleEntity extends BaseEntity implements Serializable {

    @Column(name = "ti_descripcion")
    @Basic
    private String descripcion;

    @Column(name = "ti_area")
    @Basic
    private Double area;

    @Column(name = "ti_valor_metro_cuadrado")
    @Basic
    private Double valorMetroCuadrado;

    @Column(name = "ti_valor_separacion")
    @Basic
    private Double valorSeparacion;

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Double getArea() {
        return this.area;
    }

    public void setArea(Double area) {
        this.area = area;
    }

    public Double getValorMetroCuadrado() {
        return this.valorMetroCuadrado;
    }

    public void setValorMetroCuadrado(Double valorMetroCuadrado) {
        this.valorMetroCuadrado = valorMetroCuadrado;
    }

    public Double getValorSeparacion() {
        return this.valorSeparacion;
    }

    public void setValorSeparacion(Double valorSeparacion) {
        this.valorSeparacion = valorSeparacion;
    }

}
