/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * @author jkelsy
 */
@Entity(name = "TipoPlanta")
@Table(name = "tipo_planta")
public class TipoPlantaEntity extends BaseEntity implements Serializable {

    @Basic
    private String descripcion;

    @Basic
    private Integer numeroInmuebles;

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getNumeroInmuebles() {
        return this.numeroInmuebles;
    }

    public void setNumeroInmuebles(Integer numeroInmuebles) {
        this.numeroInmuebles = numeroInmuebles;
    }

}
