/**
 * This file was generated by the Jeddict
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

@Entity(name = "TipoPlanta")
@Table(name = "tipo_planta")
public class TipoPlantaEntity implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "tpl_descripcion")
    @Basic
    private String descripcion;

    @Column(name = "tpl_nro_inmuebles")
    @Basic
    private Integer numeroInmuebles;

    @ManyToOne(targetEntity = ProyectoEntity.class)
    @JoinColumn(name = "PROYECTO_ID")
    private ProyectoEntity proyecto;
    
    @ManyToOne(targetEntity = Archivo.class)
    @JoinColumn(name = "IMAGEN_ID")
    private Archivo imagen;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getNumeroInmuebles() {
        return this.numeroInmuebles;
    }

    public void setNumeroInmuebles(Integer numeroInmuebles) {
        this.numeroInmuebles = numeroInmuebles;
    }

    public ProyectoEntity getProyecto() {
        return this.proyecto;
    }

    public void setProyecto(ProyectoEntity proyecto) {
        this.proyecto = proyecto;
    }

    public Archivo getImagen() {
        return imagen;
    }

    public void setImagen(Archivo imagen) {
        this.imagen = imagen;
    }
    
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {return false;}
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {return false;}
        final TipoPlantaEntity other = (TipoPlantaEntity) obj;
        if (!java.util.Objects.equals(this.getId(), other.getId())) {        return false;        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 41 * hash + (this.getId() != null ? this.getId().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "TipoPlantaEntity{" + " id=" + id + '}';
    }

}
