/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * @author jdmp
 */
@Entity(name = "TipoIdentificacion")
@Table(name = "tipo_identificacion")
//@NamedQuery(name = "TipoIdentificacionEntity.findByCodigo", query = "Select t from TipoIdentificacionEntity t WHERE t.codigo =:codigo")
public class TipoIdentificacionEntity extends BaseEntity implements Serializable {

    @Column(name = "tpid_codigo")
    @Basic
    private String codigo;

    @Column(name = "tpid_abreviatura")
    @Basic
    private String abreviatura;

    @Column(name = "tpid_nombre")
    @Basic
    private String nombre;

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getAbreviatura() {
        return this.abreviatura;
    }

    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
