/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * @author jdmp
 */
@Entity(name = "Torre")
@Table(name = "torre")
public class TorreEntity extends BaseEntity implements Serializable {

    @Column(name = "torre_nombre")
    @Basic
    private String nombre;

    @Column(name = "torre_direccion")
    @Basic
    private String direccion;

    @Column(name = "torre_numero")
    @Basic
    private String numero;

    @ManyToOne(targetEntity = ProyectoEntity.class)
    private ProyectoEntity proyecto;

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public ProyectoEntity getProyecto() {
        return this.proyecto;
    }

    public void setProyecto(ProyectoEntity proyecto) {
        this.proyecto = proyecto;
    }

}
