/**
 * This file was generated by the JPA Modeler
 */
package com.j2km.inmueblesgo.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * @author jkelsy
 */
@Entity(name = "Usuario")
@Table(name = "sec_usuario")
@NamedQueries({
    @NamedQuery(name = "UsuarioEntity.esAdmin", query = "Select e from Permiso e WHERE e.usuario = :usuario and e.rol.nombre = 'ADMIN'"),
    @NamedQuery(name = "UsuarioEntity.esVendedor", query = "Select e from Permiso e WHERE e.usuario = :usuario and e.rol.nombre = 'VENDEDOR'")})
public class UsuarioEntity extends BaseEntity implements Serializable {

    @Column(name = "usr_password")
    @Basic
    private String password;

    @Column(name = "usr_login", unique = true)
    @Basic
    private String login;

    @Basic
    private Boolean activo;

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public Boolean isActivo() {
        return this.activo;
    }

    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

    public Boolean getActivo() {
        return this.activo;
    }

}
